version: '3.4'

services: 
    sourcingdb:
        container_name: sourcingdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
            #- ./data:/data/db
        ports:
            -"27017:27017"

    esouring.products:
        container_name: esourcingproducts
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
        depends_on: 
            - sourcingdb
        ports:
            - "80"
            - "443"
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
            - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets